// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zngumulpqrukuzglevem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZ3VtdWxwcXJ1a3V6Z2xldmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTE3NzIsImV4cCI6MjA2MjAyNzc3Mn0.fk3_bcxDCh5wgCa1dSzx2RVdfjbCszwycM_Zz-CAdxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);